お問い合わせ部分の作成
mine2424/outsourcing_brokerage_service pull request #4
Opened 2022-07-25 17:34 UTC by code-yy

### やったこと

- Google Formに飛ばせるようにしました！

2022-07-27 12:35 UTC, mine2424 requested changes
コメントした！

2022-07-27 12:35 UTC, mine2424 commented on src/components/features/ContactButton/index.tsx
> +export const ContactButton: FC = () => {
FCのやつ
別PRと同様

2022-07-27 12:44 UTC, code-yy commented on src/components/features/ContactButton/index.tsx
> +export const ContactButton: FC = () => {
https://github.com/mine2424/outsourcing_brokerage_service/pull/3#discussion_r931014346 同文！

2022-07-27 16:00 UTC, code-yy commented
他特にレビューなければマジしといてくだちい

2022-07-28 17:43 UTC, mine2424 commented
LGTM

2022-07-28 17:43 UTC, merged